adb shell pm uninstall  --user 0 com.google.android.networkstack.tethering
adb shell pm uninstall  --user 0 com.mediatek.ims
adb shell pm uninstall  --user 0 com.android.cts.priv.ctsshim
adb shell pm uninstall  --user 0 com.android.internal.display.cutout.emulation.corner
adb shell pm uninstall  --user 0 com.oplus.smartengine
adb shell pm uninstall  --user 0 com.google.android.ext.services
adb shell pm uninstall  --user 0 com.android.internal.display.cutout.emulation.double
adb shell pm uninstall  --user 0 com.android.providers.telephony
adb shell pm uninstall  --user 0 com.oplus.securitykeyboard
adb shell pm uninstall  --user 0 com.android.dynsystem
adb shell pm uninstall  --user 0 com.oplus.crashbox
adb shell pm uninstall  --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall  --user 0 com.google.android.cellbroadcastservice
adb shell pm uninstall  --user 0 com.coloros.smartsidebar
adb shell pm uninstall  --user 0 com.android.providers.calendar
adb shell pm uninstall  --user 0 com.mediatek.telephony
adb shell pm uninstall  --user 0 com.android.providers.media
adb shell pm uninstall  --user 0 com.coloros.karaoke
adb shell pm uninstall  --user 0 com.android.networkstack.tethering.overlay
adb shell pm uninstall  --user 0 com.google.android.ext.shared
adb shell pm uninstall  --user 0 com.android.internal.systemui.navbar.gestural_wide_back
adb shell pm uninstall  --user 0 com.mediatek.location.lppe.main
adb shell pm uninstall  --user 0 com.android.wifi.resources.overlay.oplus
adb shell pm uninstall  --user 0 com.oplus.location
adb shell pm uninstall  --user 0 com.mediatek.SettingsProviderResOverlay
adb shell pm uninstall  --user 0 com.mediatek.systemuiresoverlay
adb shell pm uninstall  --user 0 com.android.launcher
adb shell pm uninstall  --user 0 com.android.networkstack.tethering.inprocess.overlay
adb shell pm uninstall  --user 0 com.oplus.screenrecorder
adb shell pm uninstall  --user 0 com.android.wifi.resources.overlay
adb shell pm uninstall  --user 0 com.android.externalstorage
adb shell pm uninstall  --user 0 com.android.htmlviewer
adb shell pm uninstall  --user 0 com.android.companiondevicemanager
adb shell pm uninstall  --user 0 com.coloros.weather.service
adb shell pm uninstall  --user 0 com.android.mms.service
adb shell pm uninstall  --user 0 com.android.providers.downloads
adb shell pm uninstall  --user 0 com.oplus.powermonitor
adb shell pm uninstall  --user 0 com.android.systemui.overlay.fingerprint.anim.ccyh
adb shell pm uninstall  --user 0 com.android.systemui.overlay.fingerprint.anim.jhsy
adb shell pm uninstall  --user 0 com.android.systemui.overlay.fingerprint.anim.jslz
adb shell pm uninstall  --user 0 com.android.systemui.overlay.fingerprint.anim.lgsy
adb shell pm uninstall  --user 0 com.android.systemui.overlay.fingerprint.anim.nlgs
adb shell pm uninstall  --user 0 com.android.systemui.overlay.fingerprint.anim.tyjw
adb shell pm uninstall  --user 0 com.android.systemui.overlay.fingerprint.anim.xklc
adb shell pm uninstall  --user 0 com.google.android.apps.messaging
adb shell pm uninstall  --user 0 com.google.android.networkstack.tethering.overlay
adb shell pm uninstall  --user 0 com.mediatek.engineermode
adb shell pm uninstall  --user 0 com.android.internal.systemui.onehanded.gestural
adb shell pm uninstall  --user 0 com.mediatek.cellbroadcastuiresoverlay
adb shell pm uninstall  --user 0 com.oplus.interconnectcollectkit
adb shell pm uninstall  --user 0 com.oplus.deepthinker
adb shell pm uninstall  --user 0 com.oplus.qualityprotect
adb shell pm uninstall  --user 0 com.oplus.apprecover
adb shell pm uninstall  --user 0 com.netflix.partner.activation
adb shell pm uninstall  --user 0 com.mediatek.omacp
adb shell pm uninstall  --user 0 com.android.bluetooth.oplus.overlay
adb shell pm uninstall  --user 0 com.android.networkstack.inprocess.overlay
adb shell pm uninstall  --user 0 android.frameworkres.overlay.display.product
adb shell pm uninstall  --user 0 com.oplus.aod
adb shell pm uninstall  --user 0 com.oplus.nhs
adb shell pm uninstall  --user 0 com.oplus.ota
adb shell pm uninstall  --user 0 com.oplus.sau
adb shell pm uninstall  --user 0 com.google.android.configupdater
adb shell pm uninstall  --user 0 com.coloros.systemclone
adb shell pm uninstall  --user 0 com.oplus.exserviceui
adb shell pm uninstall  --user 0 com.google.android.providers.media.module
adb shell pm uninstall  --user 0 com.google.android.overlay.modules.permissioncontroller
adb shell pm uninstall  --user 0 com.oplus.romupdate
adb shell pm uninstall  --user 0 com.mediatek.mt6893.gamedriver
adb shell pm uninstall  --user 0 com.coloros.focusmode
adb shell pm uninstall  --user 0 com.android.systemui.plugin.globalactions.wallet
adb shell pm uninstall  --user 0 com.google.ar.core
adb shell pm uninstall  --user 0 com.google.ar.lens
adb shell pm uninstall  --user 0 com.android.providers.downloads.ui
adb shell pm uninstall  --user 0 com.android.vending
adb shell pm uninstall  --user 0 com.android.pacprocessor
adb shell pm uninstall  --user 0 com.android.simappdialog
adb shell pm uninstall  --user 0 com.coloros.scenemode
adb shell pm uninstall  --user 0 com.android.internal.display.cutout.emulation.hole
adb shell pm uninstall  --user 0 com.android.internal.display.cutout.emulation.tall
adb shell pm uninstall  --user 0 com.android.vendors.bridge.softsim
adb shell pm uninstall  --user 0 com.android.networkstack.overlay
adb shell pm uninstall  --user 0 com.android.certinstaller
adb shell pm uninstall  --user 0 com.oplus.framework_bluetooth.overlay
adb shell pm uninstall  --user 0 com.android.carrierconfig
adb shell pm uninstall  --user 0 com.android.internal.systemui.navbar.threebutton
adb shell pm uninstall  --user 0 com.coloros.bootreg
adb shell pm uninstall  --user 0 android
adb shell pm uninstall  --user 0 com.oplus.notificationmanager
adb shell pm uninstall  --user 0 com.android.egg
adb shell pm uninstall  --user 0 com.android.mtp
adb shell pm uninstall  --user 0 com.android.nfc
adb shell pm uninstall  --user 0 com.android.ons
adb shell pm uninstall  --user 0 com.android.stk
adb shell pm uninstall  --user 0 com.oplus.locationproxy
adb shell pm uninstall  --user 0 com.android.backupconfirm
adb shell pm uninstall  --user 0 com.google.android.cellbroadcastreceiver.overlay
adb shell pm uninstall  --user 0 com.coloros.activation
adb shell pm uninstall  --user 0 com.android.statementservice
adb shell pm uninstall  --user 0 com.google.android.gm
adb shell pm uninstall  --user 0 android.autoinstalls.config.oppo
adb shell pm uninstall  --user 0 com.mediatek.mdmlsample
adb shell pm uninstall  --user 0 com.google.android.overlay.gmsconfig.common
adb shell pm uninstall  --user 0 com.oplus.audio.effectcenter
adb shell pm uninstall  --user 0 com.mediatek.smartratswitch.service
adb shell pm uninstall  --user 0 com.android.settings.intelligence
adb shell pm uninstall  --user 0 com.mediatek.frameworkresoverlay
adb shell pm uninstall  --user 0 com.debug.loggerui
adb shell pm uninstall  --user 0 com.google.android.cellbroadcastservice.overlay
adb shell pm uninstall  --user 0 com.android.internal.systemui.navbar.gestural_extra_wide_back
adb shell pm uninstall  --user 0 com.google.android.permissioncontroller
adb shell pm uninstall  --user 0 com.android.carrierconfig.oplus.overlay
adb shell pm uninstall  --user 0 com.google.android.setupwizard
adb shell pm uninstall  --user 0 com.android.providers.settings
adb shell pm uninstall  --user 0 com.android.sharedstoragebackup
adb shell pm uninstall  --user 0 com.mediatek.batterywarning
adb shell pm uninstall  --user 0 com.oplus.eyeprotect
adb shell pm uninstall  --user 0 com.oplus.callrecorder
adb shell pm uninstall  --user 0 com.google.android.overlay.modules.ext.services
adb shell pm uninstall  --user 0 com.coloros.ocs.opencapabilityservice
adb shell pm uninstall  --user 0 com.android.se
adb shell pm uninstall  --user 0 com.android.inputdevices
adb shell pm uninstall  --user 0 com.fido.asm
adb shell pm uninstall  --user 0 com.google.android.dialer
adb shell pm uninstall  --user 0 com.mediatek
adb shell pm uninstall  --user 0 com.daemon.shelper
adb shell pm uninstall  --user 0 com.google.android.captiveportallogin
adb shell pm uninstall  --user 0 com.google.android.overlay.gmsconfig.comms
adb shell pm uninstall  --user 0 com.oplus.bttestmode
adb shell pm uninstall  --user 0 com.oplus.customize.coreapp
adb shell pm uninstall  --user 0 com.google.android.apps.maps
adb shell pm uninstall  --user 0 com.oplus.uiengine
adb shell pm uninstall  --user 0 com.google.android.modulemetadata
adb shell pm uninstall  --user 0 oplus
adb shell pm uninstall  --user 0 com.android.cellbroadcastreceiver
adb shell pm uninstall  --user 0 com.google.android.webview
adb shell pm uninstall  --user 0 android.frameworkres.overlay.Network
adb shell pm uninstall  --user 0 com.coloros.weather2
adb shell pm uninstall  --user 0 com.google.android.overlay.modules.documentsui
adb shell pm uninstall  --user 0 com.google.android.networkstack
adb shell pm uninstall  --user 0 com.google.android.contacts
adb shell pm uninstall  --user 0 com.android.server.telecom
adb shell pm uninstall  --user 0 com.google.android.syncadapters.contacts
adb shell pm uninstall  --user 0 com.android.keychain
adb shell pm uninstall  --user 0 com.oplus.wirelesssettings
adb shell pm uninstall  --user 0 com.google.android.packageinstaller
adb shell pm uninstall  --user 0 com.google.android.gms
adb shell pm uninstall  --user 0 com.google.android.gsf
adb shell pm uninstall  --user 0 com.google.android.ims
adb shell pm uninstall  --user 0 com.google.android.tts
adb shell pm uninstall  --user 0 com.android.wifi.resources
adb shell pm uninstall  --user 0 com.android.calllogbackup
adb shell pm uninstall  --user 0 com.android.cameraextensions
adb shell pm uninstall  --user 0 com.android.localtransport
adb shell pm uninstall  --user 0 com.google.android.overlay.gmsconfig.gsa
adb shell pm uninstall  --user 0 com.google.android.nearby.halfsheet
adb shell pm uninstall  --user 0 com.android.carrierdefaultapp
adb shell pm uninstall  --user 0 com.oplus.uxdesign
adb shell pm uninstall  --user 0 com.coloros.lockassistant
adb shell pm uninstall  --user 0 com.android.theme.font.notoserifsource
adb shell pm uninstall  --user 0 com.mediatek.FrameworkResOverlayExt
adb shell pm uninstall  --user 0 com.android.proxyhandler
adb shell pm uninstall  --user 0 com.google.android.safetycenter.resources
adb shell pm uninstall  --user 0 com.android.internal.display.cutout.emulation.waterfall
adb shell pm uninstall  --user 0 com.oplus.appplatform
adb shell pm uninstall  --user 0 com.google.android.connectivity.resources
adb shell pm uninstall  --user 0 com.google.android.overlay.modules.permissioncontroller.forframework
adb shell pm uninstall  --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall  --user 0 com.google.android.calendar
adb shell pm uninstall  --user 0 com.oplus.engineermodeforflipkart
adb shell pm uninstall  --user 0 com.mediatek.capctrl.service
adb shell pm uninstall  --user 0 com.tencent.soter.soterserver
adb shell pm uninstall  --user 0 com.google.android.documentsui
adb shell pm uninstall  --user 0 com.google.mainline.telemetry
adb shell pm uninstall  --user 0 com.google.android.permissioncontroller.overlay.oplus
adb shell pm uninstall  --user 0 com.oplus.atlas
adb shell pm uninstall  --user 0 com.oplus.omoji
adb shell pm uninstall  --user 0 com.oplus.stdid
adb shell pm uninstall  --user 0 com.oplus.exsystemservice
adb shell pm uninstall  --user 0 com.mediatek.voicecommand
adb shell pm uninstall  --user 0 com.oplus.sauhelper
adb shell pm uninstall  --user 0 com.trustonic.teeservice
adb shell pm uninstall  --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall  --user 0 com.oplus.wallpapers
adb shell pm uninstall  --user 0 com.android.apps.tag
adb shell pm uninstall  --user 0 com.oplus.encryption
adb shell pm uninstall  --user 0 com.realme.movieshot
adb shell pm uninstall  --user 0 com.heytap.colorfulengine
adb shell pm uninstall  --user 0 com.oplus.trafficmonitor
adb shell pm uninstall  --user 0 com.google.android.networkstack.permissionconfig
adb shell pm uninstall  --user 0 com.android.storagemanager
adb shell pm uninstall  --user 0 com.ses.entitlement.o2
adb shell pm uninstall  --user 0 com.android.settings
adb shell pm uninstall  --user 0 com.oplus.wifibackuprestore
adb shell pm uninstall  --user 0 com.google.android.networkstack.overlay
adb shell pm uninstall  --user 0 com.oplus.framework.rro.realme
adb shell pm uninstall  --user 0 com.mediatek.mdmconfig
adb shell pm uninstall  --user 0 com.google.android.projection.gearhead
adb shell pm uninstall  --user 0 com.oplus.multiapp
adb shell pm uninstall  --user 0 com.oplus.engineercamera
adb shell pm uninstall  --user 0 com.oplus.postmanservice
adb shell pm uninstall  --user 0 com.mediatek.lbs.em2.ui
adb shell pm uninstall  --user 0 com.android.cts.ctsshim
adb shell pm uninstall  --user 0 com.oplus.portrait
adb shell pm uninstall  --user 0 com.google.android.overlay.modules.modulemetadata.forframework
adb shell pm uninstall  --user 0 com.heytap.accessory
adb shell pm uninstall  --user 0 com.oplus.gesture
adb shell pm uninstall  --user 0 com.android.vpndialogs
adb shell pm uninstall  --user 0 com.fido.uafclient
adb shell pm uninstall  --user 0 com.google.android.keep
adb shell pm uninstall  --user 0 com.coloros.soundrecorder
adb shell pm uninstall  --user 0 com.android.phone
adb shell pm uninstall  --user 0 com.android.shell
adb shell pm uninstall  --user 0 com.oplus.cast
adb shell pm uninstall  --user 0 com.oplus.cosa
adb shell pm uninstall  --user 0 com.oplus.cota
adb shell pm uninstall  --user 0 com.oplus.lfeh
adb shell pm uninstall  --user 0 com.oplus.onet
adb shell pm uninstall  --user 0 com.oplus.athena
adb shell pm uninstall  --user 0 com.android.wallpaperbackup
adb shell pm uninstall  --user 0 com.android.providers.blockednumber
adb shell pm uninstall  --user 0 com.android.email.partnerprovider
adb shell pm uninstall  --user 0 com.android.providers.userdictionary
adb shell pm uninstall  --user 0 com.oplus.camera
adb shell pm uninstall  --user 0 com.android.hotspot2.osulogin
adb shell pm uninstall  --user 0 com.mediatek.voiceunlock
adb shell pm uninstall  --user 0 com.android.internal.systemui.navbar.gestural
adb shell pm uninstall  --user 0 com.android.location.fused
adb shell pm uninstall  --user 0 com.android.systemui
adb shell pm uninstall  --user 0 com.android.bluetoothmidiservice
adb shell pm uninstall  --user 0 com.heytap.themestore
adb shell pm uninstall  --user 0 com.android.carrierconfig.overlay
adb shell pm uninstall  --user 0 com.android.traceur
adb shell pm uninstall  --user 0 com.google.android.cellbroadcastreceiver
adb shell pm uninstall  --user 0 com.coloros.gallery3d
adb shell pm uninstall  --user 0 android.auto_generated_rro_product__
adb shell pm uninstall  --user 0 com.oplus.nrMode
adb shell pm uninstall  --user 0 com.android.bluetooth
adb shell pm uninstall  --user 0 com.oplus.engineermode
adb shell pm uninstall  --user 0 com.android.wallpaperpicker
adb shell pm uninstall  --user 0 com.android.providers.contacts
adb shell pm uninstall  --user 0 com.oplus.screenshot
adb shell pm uninstall  --user 0 com.android.internal.systemui.navbar.gestural_narrow_back
adb shell pm uninstall  --user 0 com.oplus.subsys
adb shell pm uninstall  --user 0 com.oplus.engineernetwork
adb shell pm uninstall  --user 0 com.mediatek.gbaservice
adb shell pm uninstall  --user 0 com.wapi.wapicertmanager
adb shell pm uninstall  --user 0 com.google.android.inputmethod.latin